# Generated by Django 6.0.6 on 2026-06-08 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('reflective', 'Reflective'), ('joyful', 'Joyful'), ('dark', 'Dark'), ('romantic', 'Romantic'), ('adventure', 'Adventure'), ('melancholy', 'Melancholy'), ('curious', 'Curious'), ('bold', 'Bold')], default='reflective', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
